version: '3.8'

services:
    comfyui:
        build: .
        ports:
            - '8188:8188'
        volumes:
            - ./models:/app/models
            - ./output:/app/output
        restart: unless-stopped
